version: "3.8"
services:
  gendiff:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    - .:/usr/src/app
    image: hexlet:gendiff
    container_name: hexlet_gendiff

  gendiff_dev:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    - .:/usr/src/app
    - $HOME/asciinema-id:/root/.config/asciinema/install-id
    image: hexlet:gendiff
    container_name: hexlet_gendiff
